CREATE TABLE usuarios (
   id BIGINT NOT NULL AUTO_INCREMENT,
   login VARCHAR(50) NOT NULL,
   senha VARCHAR(100) NOT NULL,
   nome VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   data_nascimento DATE NOT NULL,
   cpf VARCHAR(11) NOT NULL,
   sexo VARCHAR(10) NOT NULL,
   PRIMARY KEY (id),
   UNIQUE KEY (login)
 );


